name: API sprint-1

on:
  push:
    branches:
      - feature/sprint-1
      - develop
      - main
    paths:
      - 'docker-compose.yml'
      - .github/workflows/backend.yml

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name:
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Make mvnw executable
        run:  chmod +x ./mvnw

      - name: Compile project
        run: chmod +x ./mvnw

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name:
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make mvnw executable
        run: chmod +x ./mvnw

      - name: Running unit Tests
        run: chmod +x ./mvnw

  build:
    runs-on: ubuntu-latest
    name: Build backend
    needs: [compile , unit-tests]
    steps:
      - name:
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Make mvnw executable
        run: chmod +x ./mvnw

      - name: Build project
        run: chmod +x ./mvnw

  build-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name:
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make mvnw executable
        run: chmod +x ./mvnw
